#!/bin/dash

if [ $# -ne 2 ];then
    echo "usage: mygive-test <assignment> <filename>" >&2
    exit 1
fi

asm=$1
file=$2

if ! echo "$asm" | grep -q "^[a-z][a-zA-Z0-9_]*$";then
    echo "mygive-test: invalid assignment: $asm" >&2
    exit 1
fi

if ! echo "$file" | grep -Eq "^[a-zA-Z0-9_\-\.\/]";then
    echo "mygive-test: invalid filename: $file" >&2
    exit 1
fi

[ -d ".mygive/assignments/$asm" ] || { 
    echo "mygive-test: assignment $asm not found" >&2; exit 1 
    }

des_path=".mygive/assignments/$asm/tests"
pass=0
fail=0
for d in $des_path;do
    file_name=$(find $d -mindepth 1 -maxdepth 1 -type d | cut -d'/' -f5 | sort)
    # suppose every filename with marking has mark file and filename without marking don't has mark file
    for f in $file_name;do
        if echo $f | grep -q 'mark' ;then
            continue
        else
            options=$(cat $des_path/$f/options 2>/dev/null) 
            stdout=$(cat $des_path/$f/stdout 2>/dev/null) 
            arguments=$(cat $des_path/$f/arguments 2>/dev/null) 
            stdin=$(cat $des_path/$f/stdin 2>/dev/null)  
            exit_status=$(cat $des_path/$f/exit_status 2>/dev/null) 
            stderr=$(cat $des_path/$f/stderr 2>/dev/null) 
            file_stdout=$(mktemp)
            file_stderr=$(mktemp)
            desired_output=$(mktemp)
            stdout_nonoption=$(echo "$stdin" | "$file" $arguments 2>"$file_stderr") 
            stdout_option="$stdout_nonoption"
            stdout_standard="$stdout"
            if echo $options | grep -q 'c';then
                stdout_option=$(echo "$stdout_option" | tr '[:upper:]' '[:lower:]')
                stdout_standard=$(echo "$stdout_standard" | tr '[:upper:]' '[:lower:]')
            fi
            if echo $options | grep -q 'w';then
                stdout_option=$(echo "$stdout_option"  |tr -s '[:space:]' ' ')
                stdout_standard=$(echo "$stdout_standard" | tr -s '[:space:]' ' ')
            fi
            if echo $options | grep -q 'b';then
                stdout_option=$(echo "$stdout_option" | grep -v '^$'| tr '\n' ' ')
                stdout_standard=$(echo "$stdout_standard" | grep -v '^$'| tr '\n' ' ')
            fi
            if echo $options | grep -q 'd';then
                stdout_option=$(echo "$stdout_option" | tr -cd '[:alpha:][:space:]\n')
                stdout_standard=$(echo "$stdout_standard" | tr -cd '[:alpha:][:space:]\n')
            fi
            echo "$stdout_option" >"$file_stdout" 
            echo "$stdout_standard" >"$desired_output"
            stdout_tempfile=$(mktemp)
            stdout_standard_tempfile=$(mktemp)
            echo "$stdout_nonoption" > "$stdout_tempfile"
            echo "$stdout_standard" > "$stdout_standard_tempfile"

            if ! cmp -s "$file_stdout" "$desired_output"; then
                echo "* Test $f failed."
                printf -- "--- Incorrect stdout of $(wc -c < "$stdout_tempfile") bytes:\n"
                cat "$stdout_tempfile"
                echo ""
                printf -- "--- Correct stdout is these $(wc -c < "$stdout_standard_tempfile") bytes:\n"
                cat "$stdout_standard_tempfile"
                echo ""
                fail=$((fail + 1))
                continue
            else
                echo "* Test $f passed."
                pass=$((pass + 1))
            fi
        fi
    done
done
echo "** $pass tests passed, $fail tests failed"

