#!/bin/dash

if [ $# -ne 2 ] && [ $# -ne 3 ];then
    echo "usage: mygive-fetch <assignment> <zid> [n]" >&2
    exit 1
fi

asm=$1
zid=$2
num=${3:-0}

if ! echo "$asm" | grep -q "^[a-z][a-zA-Z0-9_]*$";then
    echo "mygive-fetch: invalid assignment: $asm" >&2
    exit 1
fi

if ! echo "$zid" | grep -Eq "^z[0-9]{7}$";then
    echo "mygive-fetch: invalid zid: $zid" >&2
    exit 1
fi

[ -d ".mygive/assignments/$asm" ] || { 
    echo "mygive-fetch: assignment $asm not found" >&2; exit 1 
    }
[ -d ".mygive/assignments/$asm/submissions/$zid" ] || { 
    echo "mygive-fetch: no submission for $asm" >&2; exit 1 
    }
n=$(find ".mygive/assignments/$asm/submissions/$zid" -mindepth 1 -maxdepth 1 -type d 2>/dev/null|wc -l)
if [ $num -gt 0 ];then
    if [ $num -le $n ];then
        submitted_file=$(find ".mygive/assignments/$asm/submissions/$zid/$num" -mindepth 1 -maxdepth 1 -type f | grep -v 'meta' | head -n1)
        cat $submitted_file
    else
        echo "mygive-fetch: submission $num not found for $asm" >&2
        exit 1
    fi
else    
    num_correct=$((n + num))
    if [ $num_correct -le 0 ];then
        echo "mygive-fetch: submission $num not found for $asm" >&2
        exit 1
    else
        submitted_file=$(find ".mygive/assignments/$asm/submissions/$zid/$num_correct" -mindepth 1 -maxdepth 1 -type f | grep -v 'meta' |head -n1)
        cat $submitted_file
    fi
fi
